parameters:
    ibexa.http_cache.store.root: "%kernel.cache_dir%/http_cache"
    ibexa.http_cache.invalidate_token.ttl: 86400
    ibexa.http_cache.no_vary.routes: ['ezplatform.httpcache.invalidatetoken']
