parameters:
    ibexa.http_cache.store.root: "%kernel.cache_dir%/http_cache"
    ibexa.http_cache.invalidate_token.ttl: 86400
    ibexa.http_cache.no_vary.routes: ['ibexa.http_cache.invalidate_token']
    ibexa.http_cache.translation_aware.enabled.default_value: false
    ibexa.http_cache.translation_aware.enabled: "%env(default:ibexa.http_cache.translation_aware.enabled.default_value:bool:HTTPCACHE_TRANSLATION_AWARE_ENABLED)%"
